appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: YkhXG+nAlS+DM/jvWkpCBOKCCDt9L9okZnkfUByUqZ3XurNXycMOCE4d8hVX6vo95Wx1N7FC2+u2bwzs4uk4a8flbJ/FbWrrXfvqFDpBeql/Q9Ay5Q1UPUt5kJEN24Nk6z2r+iJTQiMjV3DJPj1giGExQlOvydwjpg+7CXybLQHdO1YvPmsWrMOrTGEv+HlNgYqWp8I6oudiT/WPWpVYp8rdmGvaO+RSGxjXQsdw5yUXXj7PKNmMNNchEsZ5efD5JWPozBDCbZdyDaDQeMROBLGjegI1qSNwiCOhoJTdS5KpsSiQD5hR+alPQNElmTVVU5fF99XX4HGWH354+bYfuET9Fn045HmXnnN2+np4DSCeBc/s8gAlq2G1eoK8NTk80RHM29Jg8QEZbdCmIUbjQZNqsuzSuL3MnVg7nMQeR0Klmh5gURwpddp36sZvRxMfXIjIC81hyFZlV9UINYvRk+c71rb0AhOryhryh/QpFMRT7Ew+HHFvKguH9W9mbZFCBsLe8SKI8Fjh44BSUvtsff0WCEHZi7BqgUhBWv6c0hbJR/LDnff/20nbOJbUEmq//1NA/Up/KZRdTARumkKkVfbP1U2yd+zULw3EJxxky604FLQGy7mHOG3DGrfOfBx7hoCNr5J01lxMDQerS6gRoCkSWJyqKaXqo6wyFaY15rs=
conda_forge_output_validation: true
